---
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/aslafy-z)
      - prefix(gitlab.com/aslafy-z)
  forbidigo:
    forbid:
      - ^print.*$
      - ^fmt\.Print.*$
  misspell:
    locale: "US"

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - errname
    - exhaustive
    - forbidigo
    - gci
    - gocritic
    - godot
    - goimports
    - gomodguard
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - typecheck
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - gosec
    - path: _test\.go
      linters:
        - revive
      text: unused-parameter
