x- gitlab-runner: &gitlab-runner
  build:
    dockerfile: dev/Dockerfile
  entrypoint: []
  environment:
    CONFIG_FILE: config.toml
    FLEETING_PLUGIN_PATH: /opt
  working_dir: /opt
  volumes:
    - ./dev/files:/opt

services:
  # init:
  #   <<: *gitlab-runner
  #   command:
  #     - gitlab-runner
  #     - fleeting
  #     - install

  run:
    <<: *gitlab-runner
    command:
      - gitlab-runner
      - run
    ports:
      - 9252:9252
    depends_on:
      - proxy
    # depends_on:
    #   init:
    #     condition: service_completed_successfully

  proxy:
    image: mitmproxy/mitmproxy
    command:
      - mitmweb
      - --mode
      - reverse:https://api.scaleway.com
      - --web-host
      - 0.0.0.0
    ports:
      - 8081:8081
