package instancegroup

type Config struct {
	// Location is the Scaleway "Zone" name to create the server in.
	// Refer to https://www.scaleway.com/en/docs/account/reference-content/products-availability/ to list available zones.
	Zone string

	// ServerNamePrefix is the prefix of the server name. The server name will be
	// generated by appending a random suffix to this prefix.
	ServerNamePrefix string

	// Server Type is the Scaleway "Server Type" (name or id) to create the server with.
	// Run `scw instance server-type list` to list available server types.
	ServerType string

	// Image is the Scaleway "Image" (name or id) to create the server with. Run
	// `scw image list` to list available images.
	Image string

	// UserData is the data available to initialization framework that may run after the
	// server boot.
	UserData string

	// VolumeSize is the size in GB of the volume that will be attached to the server.
	VolumeSize int

	// Tags is a list of tags to apply to the server.
	Tags []string
}
