release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  dependencies:
    - upload-binaries
  extends:
    - .rules:release:all
  script:
    - apk add make bash curl
    - make release

release-oci:
  stage: release
  image: golang:$GO_VERSION-alpine
  dependencies:
    - binaries
  extends:
    - .rules:release:all
  script:
    - apk add --update make git bash
    - make release-oci-artifacts
