pre-commit:
  stage: test
  image: python:3.12
  extends:
    - .rules:merge_request_or_release
  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
    PRE_COMMIT_HOME: $CI_PROJECT_DIR/.cache/pre-commit
    GOLANGCI_LINT_CACHE: $CI_PROJECT_DIR/.cache/golangci-lint
  cache:
    - key: pre-commit-pip
      paths: [$PIP_CACHE_DIR]
    - key:
        prefix: pre-commit-home
        files: [.pre-commit-config.yaml]
      paths: [$PRE_COMMIT_HOME]
    - key: golangci-lint
      paths: [$GOLANGCI_LINT_CACHE]
  script:
    - pip install pre-commit
    - pre-commit run --all --color=always --show-diff-on-failure

test:
  stage: test
  image: golang:$GO_VERSION
  extends:
    - .rules:merge_request_or_release
    - .go-cache
  before_script:
    - >
      if $CI_COMMIT_REF_PROTECTED; then
        export HCLOUD_TOKEN="$(hack/get-tmp-hcloud-token.sh)";
      fi
  script:
    - make test
